abbr --add gf "git fetch --all --prune"
abbr --add gff "git merge --ff-only origin/(git branch --show-current)"
abbr --add glo "git log --graph --all"
abbr --add gp "git push --follow-tags"
abbr --add gpp "git push --follow-tags --set-upstream origin (git branch --show-current)"
